version: "3.9"

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
      
 # Node API service
  api: 
    build: .
    ports:
      - 5000:4242
    environment:
      PORT: 4242
      MONGODB_URI: mongodb://mongo_db:27017?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.3.0
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}